name: "kind"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: asdf_install
      uses: asdf-vm/actions/install@v1
    - name: Testing
      run: |
        kind create cluster --config kind.conf
        kubectl cluster-info
        kubectl get pods -n kube-system
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
        kubectl apply -f prow-starter-s3.template.yaml
